# Generated by Django 4.1.7 on 2023-09-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('global_name', models.CharField(max_length=64)),
                ('avatar', models.CharField(max_length=64)),
                ('flags', models.IntegerField()),
                ('public_flags', models.IntegerField()),
                ('last_login', models.DateTimeField()),
            ],
        ),
    ]
