# Generated by Django 4.1.7 on 2023-09-25 11:45

import discord_auth.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discorduser',
            managers=[
                ('objects', discord_auth.managers.DiscordUserOAuth2Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='discorduser',
            name='flags',
        ),
        migrations.RemoveField(
            model_name='discorduser',
            name='public_flags',
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='avatar',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='global_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='username',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
