# Generated by Django 4.0.4 on 2023-10-02 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_version', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ChampionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=256)),
                ('champion', models.CharField(max_length=32)),
                ('win', models.BooleanField()),
                ('damageDealtToBuildings', models.IntegerField()),
                ('damageDealtToObjectives', models.IntegerField()),
                ('damageDealtToTurrets', models.IntegerField()),
                ('damageSelfMitigated', models.IntegerField()),
                ('goldEarned', models.IntegerField()),
                ('goldSpent', models.IntegerField()),
                ('magicDamageDealt', models.IntegerField()),
                ('magicDamageDealtToChampions', models.IntegerField()),
                ('magicDamageTaken', models.IntegerField()),
                ('physicalDamageDealt', models.IntegerField()),
                ('physicalDamageDealtToChampions', models.IntegerField()),
                ('physicalDamageTaken', models.IntegerField()),
                ('totalDamageDealt', models.IntegerField()),
                ('totalDamageDealtToChampions', models.IntegerField()),
                ('totalDamageTaken', models.IntegerField()),
                ('trueDamageDealt', models.IntegerField()),
                ('trueDamageDealtToChampions', models.IntegerField()),
                ('trueDamageTaken', models.IntegerField()),
                ('totalHeal', models.IntegerField()),
                ('totalHealsOnTeammates', models.IntegerField()),
                ('totalDamageShieldedOnTeammates', models.IntegerField()),
                ('timeCCingOthers', models.IntegerField()),
                ('totalTimeCCDealt', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champion_api.match')),
            ],
        ),
    ]
