# Generated by Django 4.0.4 on 2023-10-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champion_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championdata',
            name='match',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
