# Generated by Django 4.1.7 on 2023-10-02 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champion_api', '0003_match_championdata_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='championdata',
            old_name='champion',
            new_name='championName',
        ),
    ]
