# Generated by Django 4.0.4 on 2023-10-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champion_api', '0004_rename_champion_championdata_championname'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_length',
            field=models.BigIntegerField(default=901),
            preserve_default=False,
        ),
    ]
