# Generated by Django 4.0.4 on 2023-10-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champion_api', '0005_match_game_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='data_version',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_length',
            field=models.IntegerField(null=True),
        ),
    ]
